version: '3'
services:
  web:
    restart: always
    build: .
    image: sonwy102/skin-app:v2
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --bind :8000 --workers 3 skin_app.wsgi:application
  db:
    image: postgres
    environment:
      - POSTGRES_DB=skin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
