# Generated by Django 3.0.8 on 2020-08-04 03:21

from django.db import migrations, models
import django.db.models.deletion
import product_search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, choices=[(product_search.models.CountryChoice['US'], 'US'), (product_search.models.CountryChoice['KR'], 'Korea'), (product_search.models.CountryChoice['JP'], 'Japan')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, max_length=500, upload_to=product_search.models.get_image_path)),
                ('imglink', models.URLField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_search.Brand')),
                ('ingredients', models.ManyToManyField(blank=True, to='product_search.Ingredient')),
            ],
        ),
    ]
