# Generated by Django 3.0.8 on 2020-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0002_auto_20200804_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imglink',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
